# Generated by Django 4.1.7 on 2023-03-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apparel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('color', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=40)),
                ('type', models.CharField(choices=[('T', 'Top'), ('B', 'Bottom'), ('S', 'Shoe')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('date', models.DateField(verbose_name='Date Made')),
                ('event', models.CharField(max_length=40)),
                ('caption', models.CharField(max_length=50)),
            ],
        ),
    ]
