# Generated by Django 4.1.7 on 2023-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='img',
            field=models.ImageField(default='images/img-error.png', upload_to=''),
        ),
    ]
