# Generated by Django 4.1.7 on 2023-03-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_apparel_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='apparel',
            name='style',
            field=models.CharField(default='not specified', max_length=70),
        ),
    ]
