# Generated by Django 4.1.7 on 2023-03-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_apparel_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='clothing',
            field=models.ManyToManyField(to='main_app.apparel'),
        ),
    ]
