# Generated by Django 4.1.7 on 2023-03-10 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_outfit_clothing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='clothing',
            new_name='apparels',
        ),
    ]
